name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:

    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Upgrade pip, install ruff, pytest, and black
        # Optionally, install additional dependencies from requirements.txt

      - name: Lint with Ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff  .
        # Perform linting using Ruff

      - name: Format with Black
        run: |
          black .
        # Format the code using Black

      - name: Test with pytest
        run: |
          pytest
        # Run tests using pytest
